import Head from 'next/head'
function About() {
  return (
    <div>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          hello
        </h1>
      </main>
    </div>
  )
}

export default About;